import { Dict } from "../dictionary";

export type GoalKey = "lose" | "gain" | "maintain" | "sleep" | "gut";

export interface GoalSetupDict {
  ttl: string;
  sub: string;
  bodyLbl: string;
  bodySub: string;
  goals: Record<GoalKey, string>;
  goalsSub: Record<GoalKey, string>;
  rows: { weight: string; height: string; goalWeight: string; bodyfat: string; muscle: string };
  opt: string;
  start: string;
  med: string;
  kg: string;
  cm: string;
  pct: string;
}

export const GOALS: { key: GoalKey; icon: string; needsWeight: boolean }[] = [
  { key: "lose", icon: "IconFlame", needsWeight: true },
  { key: "gain", icon: "IconBarbell", needsWeight: true },
  { key: "maintain", icon: "IconHeart", needsWeight: false },
  { key: "sleep", icon: "IconMoon", needsWeight: false },
  { key: "gut", icon: "IconDroplet", needsWeight: false }
];

export const goalSetupDict: Dict<GoalSetupDict> = {
  ja: { ttl: "目指すことを、選びましょう", sub: "いくつ選んでも大丈夫。あとから設定でいつでも変えられます。", bodyLbl: "いまの体", bodySub: "分かる範囲で大丈夫。体脂肪率や筋肉量は、あとでも入れられます。", goals: { lose: "減量したい", gain: "筋肉をつけたい", maintain: "維持・健康", sleep: "睡眠を改善したい", gut: "腸内環境を整えたい" }, goalsSub: { lose: "体重をゆっくり落とす", gain: "バルクアップ", maintain: "いまの調子を保つ", sleep: "よく眠れるように", gut: "お通じ・腸活" }, rows: { weight: "体重", height: "身長", goalWeight: "目標体重", bodyfat: "体脂肪率", muscle: "筋肉量" }, opt: "体脂肪率・筋肉量を入れる（任意）", start: "はじめる", med: "入力された数値やこの先の提案は、あくまで目安です。医療上の診断・治療を目的とするものではありません。", kg: "kg", cm: "cm", pct: "%" },
  en: { ttl: "Choose what you're aiming for", sub: "Pick as many as you like. You can change these anytime in settings.", bodyLbl: "Your body now", bodySub: "Whatever you know is fine. Body fat and muscle can be added later.", goals: { lose: "Lose weight", gain: "Build muscle", maintain: "Maintain / health", sleep: "Improve sleep", gut: "Improve gut health" }, goalsSub: { lose: "drop weight slowly", gain: "bulk up", maintain: "keep your current shape", sleep: "sleep better", gut: "digestion & gut care" }, rows: { weight: "Weight", height: "Height", goalWeight: "Goal weight", bodyfat: "Body fat", muscle: "Muscle" }, opt: "Add body fat & muscle (optional)", start: "Get started", med: "The values you enter and the suggestions ahead are estimates only. They are not intended for medical diagnosis or treatment.", kg: "kg", cm: "cm", pct: "%" },
  "zh-Hans": { ttl: "选择你的目标", sub: "选几个都可以。以后可在设置中随时更改。", bodyLbl: "现在的身体", bodySub: "知道多少填多少。体脂率和肌肉量以后也能补。", goals: { lose: "想减重", gain: "想增肌", maintain: "维持·健康", sleep: "想改善睡眠", gut: "想调理肠道" }, goalsSub: { lose: "慢慢减重", gain: "增肌", maintain: "保持现状", sleep: "睡得更好", gut: "通便·肠道养护" }, rows: { weight: "体重", height: "身高", goalWeight: "目标体重", bodyfat: "体脂率", muscle: "肌肉量" }, opt: "填写体脂率·肌肉量（可选）", start: "开始", med: "输入的数值和之后的建议仅供参考，并非以医疗诊断或治疗为目的。", kg: "kg", cm: "cm", pct: "%" },
  "zh-Hant": { ttl: "選擇你的目標", sub: "選幾個都可以。之後可在設定中隨時更改。", bodyLbl: "現在的身體", bodySub: "知道多少填多少。體脂率和肌肉量以後也能補。", goals: { lose: "想減重", gain: "想增肌", maintain: "維持·健康", sleep: "想改善睡眠", gut: "想調理腸道" }, goalsSub: { lose: "慢慢減重", gain: "增肌", maintain: "保持現狀", sleep: "睡得更好", gut: "通便·腸道養護" }, rows: { weight: "體重", height: "身高", goalWeight: "目標體重", bodyfat: "體脂率", muscle: "肌肉量" }, opt: "填寫體脂率·肌肉量（可選）", start: "開始", med: "輸入的數值和之後的建議僅供參考，並非以醫療診斷或治療為目的。", kg: "kg", cm: "cm", pct: "%" },
  ko: { ttl: "목표를 골라보세요", sub: "몇 개든 괜찮아요. 나중에 설정에서 언제든 바꿀 수 있어요.", bodyLbl: "지금의 몸", bodySub: "아는 만큼이면 돼요. 체지방률과 근육량은 나중에도 넣을 수 있어요.", goals: { lose: "감량하고 싶어요", gain: "근육을 키우고 싶어요", maintain: "유지·건강", sleep: "수면을 개선하고 싶어요", gut: "장 건강을 챙기고 싶어요" }, goalsSub: { lose: "천천히 체중 감량", gain: "벌크업", maintain: "지금 상태 유지", sleep: "잘 자기 위해", gut: "배변·장 관리" }, rows: { weight: "체중", height: "키", goalWeight: "목표 체중", bodyfat: "체지방률", muscle: "근육량" }, opt: "체지방률·근육량 입력(선택)", start: "시작하기", med: "입력한 수치와 앞으로의 제안은 어디까지나 예상치이며, 의료상 진단·치료를 목적으로 하지 않습니다.", kg: "kg", cm: "cm", pct: "%" },
  th: { ttl: "เลือกสิ่งที่ตั้งเป้า", sub: "เลือกกี่อย่างก็ได้ เปลี่ยนได้ทุกเมื่อในการตั้งค่า", bodyLbl: "ร่างกายตอนนี้", bodySub: "รู้เท่าไหร่ก็กรอกเท่านั้น ไขมันและกล้ามเนื้อใส่ทีหลังได้", goals: { lose: "อยากลดน้ำหนัก", gain: "อยากเพิ่มกล้าม", maintain: "คงสภาพ·สุขภาพ", sleep: "อยากนอนหลับดีขึ้น", gut: "อยากดูแลลำไส้" }, goalsSub: { lose: "ลดน้ำหนักช้าๆ", gain: "เพิ่มกล้าม", maintain: "รักษาสภาพปัจจุบัน", sleep: "หลับสบายขึ้น", gut: "ขับถ่าย·ดูแลลำไส้" }, rows: { weight: "น้ำหนัก", height: "ส่วนสูง", goalWeight: "น้ำหนักเป้าหมาย", bodyfat: "ไขมัน", muscle: "กล้ามเนื้อ" }, opt: "กรอกไขมัน·กล้ามเนื้อ (ถ้ามี)", start: "เริ่ม", med: "ตัวเลขที่กรอกและคำแนะนำต่อจากนี้เป็นเพียงค่าประมาณ ไม่ได้มีวัตถุประสงค์เพื่อการวินิจฉัยหรือรักษาทางการแพทย์", kg: "กก.", cm: "ซม.", pct: "%" },
  hi: { ttl: "अपने लक्ष्य चुनें", sub: "जितने चाहें चुनें। सेटिंग में कभी भी बदल सकते हैं।", bodyLbl: "अभी का शरीर", bodySub: "जितना पता हो उतना ठीक है। फैट और मसल बाद में भी डाल सकते हैं।", goals: { lose: "वज़न घटाना", gain: "मसल बढ़ाना", maintain: "बनाए रखना·सेहत", sleep: "नींद सुधारना", gut: "आँत की सेहत सुधारना" }, goalsSub: { lose: "धीरे-धीरे वज़न कम", gain: "बल्क अप", maintain: "मौजूदा स्थिति बनाए रखें", sleep: "बेहतर नींद", gut: "पाचन·आँत की देखभाल" }, rows: { weight: "वज़न", height: "कद", goalWeight: "लक्ष्य वज़न", bodyfat: "शरीर फैट", muscle: "मसल" }, opt: "फैट·मसल डालें (वैकल्पिक)", start: "शुरू करें", med: "दर्ज किए गए मान और आगे के सुझाव केवल अनुमान हैं। ये चिकित्सा निदान या उपचार के लिए नहीं हैं।", kg: "kg", cm: "cm", pct: "%" },
  fr: { ttl: "Choisissez vos objectifs", sub: "Autant que vous voulez. Modifiable à tout moment dans les réglages.", bodyLbl: "Votre corps aujourd'hui", bodySub: "Ce que vous savez suffit. Masse grasse et muscle s'ajoutent plus tard.", goals: { lose: "Perdre du poids", gain: "Prendre du muscle", maintain: "Maintien / santé", sleep: "Améliorer le sommeil", gut: "Améliorer la digestion" }, goalsSub: { lose: "perdre du poids doucement", gain: "prise de masse", maintain: "garder la forme actuelle", sleep: "mieux dormir", gut: "transit & flore" }, rows: { weight: "Poids", height: "Taille", goalWeight: "Poids cible", bodyfat: "Masse grasse", muscle: "Muscle" }, opt: "Ajouter masse grasse & muscle (facultatif)", start: "Commencer", med: "Les valeurs saisies et les suggestions à venir sont indicatives. Elles ne sont pas destinées à un diagnostic ou un traitement médical.", kg: "kg", cm: "cm", pct: "%" },
  es: { ttl: "Elige tus objetivos", sub: "Elige los que quieras. Puedes cambiarlos cuando quieras en ajustes.", bodyLbl: "Tu cuerpo ahora", bodySub: "Con lo que sepas basta. Grasa y músculo se añaden después.", goals: { lose: "Bajar de peso", gain: "Ganar músculo", maintain: "Mantener / salud", sleep: "Mejorar el sueño", gut: "Mejorar la salud intestinal" }, goalsSub: { lose: "bajar peso poco a poco", gain: "aumentar volumen", maintain: "mantener tu forma actual", sleep: "dormir mejor", gut: "digestión y flora" }, rows: { weight: "Peso", height: "Altura", goalWeight: "Peso objetivo", bodyfat: "Grasa corporal", muscle: "Músculo" }, opt: "Añadir grasa y músculo (opcional)", start: "Empezar", med: "Los valores que ingresas y las sugerencias siguientes son estimaciones. No están destinados a diagnóstico ni tratamiento médico.", kg: "kg", cm: "cm", pct: "%" },
  de: { ttl: "Wähle deine Ziele", sub: "So viele du willst. Jederzeit in den Einstellungen änderbar.", bodyLbl: "Dein Körper jetzt", bodySub: "Was du weißt, reicht. Körperfett und Muskeln gehen später.", goals: { lose: "Abnehmen", gain: "Muskeln aufbauen", maintain: "Halten / Gesundheit", sleep: "Schlaf verbessern", gut: "Darmgesundheit verbessern" }, goalsSub: { lose: "langsam abnehmen", gain: "Masse aufbauen", maintain: "aktuelle Form halten", sleep: "besser schlafen", gut: "Verdauung & Darm" }, rows: { weight: "Gewicht", height: "Größe", goalWeight: "Zielgewicht", bodyfat: "Körperfett", muscle: "Muskeln" }, opt: "Körperfett & Muskeln (optional)", start: "Loslegen", med: "Die eingegebenen Werte und die folgenden Vorschläge sind Schätzungen. Sie dienen nicht der medizinischen Diagnose oder Behandlung.", kg: "kg", cm: "cm", pct: "%" },
  it: { ttl: "Scegli i tuoi obiettivi", sub: "Quanti vuoi. Modificabili in qualsiasi momento nelle impostazioni.", bodyLbl: "Il tuo corpo ora", bodySub: "Va bene quel che sai. Massa grassa e muscoli si aggiungono dopo.", goals: { lose: "Dimagrire", gain: "Mettere muscoli", maintain: "Mantenere / salute", sleep: "Migliorare il sonno", gut: "Migliorare l'intestino" }, goalsSub: { lose: "perdere peso piano", gain: "massa muscolare", maintain: "mantenere la forma attuale", sleep: "dormire meglio", gut: "digestione & flora" }, rows: { weight: "Peso", height: "Altezza", goalWeight: "Peso obiettivo", bodyfat: "Massa grassa", muscle: "Muscolo" }, opt: "Aggiungi massa grassa & muscoli (facoltativo)", start: "Inizia", med: "I valori inseriti e i suggerimenti successivi sono stime. Non sono destinati a diagnosi o trattamenti medici.", kg: "kg", cm: "cm", pct: "%" },
  pt: { ttl: "Escolha seus objetivos", sub: "Escolha quantos quiser. Pode mudar quando quiser nas configurações.", bodyLbl: "Seu corpo agora", bodySub: "O que você souber já basta. Gordura e músculo dá pra adicionar depois.", goals: { lose: "Emagrecer", gain: "Ganhar músculo", maintain: "Manter / saúde", sleep: "Melhorar o sono", gut: "Melhorar o intestino" }, goalsSub: { lose: "perder peso devagar", gain: "ganhar massa", maintain: "manter a forma atual", sleep: "dormir melhor", gut: "digestão & flora" }, rows: { weight: "Peso", height: "Altura", goalWeight: "Peso alvo", bodyfat: "Gordura corporal", muscle: "Músculo" }, opt: "Adicionar gordura & músculo (opcional)", start: "Começar", med: "Os valores inseridos e as sugestões seguintes são estimativas. Não se destinam a diagnóstico ou tratamento médico.", kg: "kg", cm: "cm", pct: "%" },
  vi: { ttl: "Chọn mục tiêu của bạn", sub: "Chọn bao nhiêu cũng được. Đổi bất cứ lúc nào trong cài đặt.", bodyLbl: "Cơ thể hiện tại", bodySub: "Biết bao nhiêu điền bấy nhiêu. Mỡ và cơ có thể thêm sau.", goals: { lose: "Giảm cân", gain: "Tăng cơ", maintain: "Duy trì / sức khỏe", sleep: "Cải thiện giấc ngủ", gut: "Cải thiện đường ruột" }, goalsSub: { lose: "giảm cân từ từ", gain: "tăng khối lượng", maintain: "giữ dáng hiện tại", sleep: "ngủ ngon hơn", gut: "tiêu hóa & đường ruột" }, rows: { weight: "Cân nặng", height: "Chiều cao", goalWeight: "Cân nặng mục tiêu", bodyfat: "Mỡ cơ thể", muscle: "Cơ" }, opt: "Thêm mỡ & cơ (tùy chọn)", start: "Bắt đầu", med: "Các giá trị bạn nhập và gợi ý phía sau chỉ là ước tính. Chúng không nhằm mục đích chẩn đoán hay điều trị y tế.", kg: "kg", cm: "cm", pct: "%" },
  id: { ttl: "Pilih tujuanmu", sub: "Pilih sebanyak yang kamu mau. Bisa diubah kapan saja di pengaturan.", bodyLbl: "Tubuhmu sekarang", bodySub: "Seadanya yang kamu tahu. Lemak dan otot bisa ditambah nanti.", goals: { lose: "Turun berat", gain: "Bangun otot", maintain: "Jaga / kesehatan", sleep: "Perbaiki tidur", gut: "Perbaiki kesehatan usus" }, goalsSub: { lose: "turun berat perlahan", gain: "bulking", maintain: "jaga bentuk sekarang", sleep: "tidur lebih nyenyak", gut: "pencernaan & usus" }, rows: { weight: "Berat", height: "Tinggi", goalWeight: "Berat target", bodyfat: "Lemak tubuh", muscle: "Otot" }, opt: "Tambah lemak & otot (opsional)", start: "Mulai", med: "Nilai yang kamu masukkan dan saran berikutnya hanya perkiraan. Bukan untuk diagnosis atau pengobatan medis.", kg: "kg", cm: "cm", pct: "%" }
};
